feat(Link,Button): adds lowercase variant to Link and Button components
dequelabs/cauldron pull request #1065
Opened 2023-05-05 05:12 UTC by tbusillo

## Description 
- Adds new variant to the `<Button />` and `<Link />` components that transforms text content to lowercase. 
- Updates the `Link` documentation to use the new MDX format
- Adds tests for the new variant(s)

2023-05-05 05:37 UTC, tbusillo commented on docs/components/example.css
> +  margin: 0 var(--space-smaller);
Added this in so there would be space between the examples where buttons are adjacent to a link. It was looking crowded without this. 

<img width="783" alt="CleanShot 2023-05-05 at 01 35 32@2x" src="https://user-images.githubusercontent.com/1016306/236384198-a46ea7f1-183a-4e51-ab7c-7279fa037e69.png">

2023-05-08 15:45 UTC, dequejosie commented on packages/react/src/components/Button/index.tsx
> +        'Link--lowercase': lowercase
`Button--lowercase`?

2023-05-08 15:51 UTC, dequejosie commented on docs/pages/components/Link.mdx
> +description: A link component with accessible styling.
Do we need to define what `link` is like what we do with `button`?

2023-05-08 15:52 UTC, dequejosie commented on docs/pages/components/Link.mdx
> +      description: 'Ref function for the button element'
nit: Period at the end.

2023-05-08 15:54 UTC, dequejosie commented on docs/pages/components/Link.mdx
> +
nit: a primary button?

2023-05-10 13:48 UTC, scurker requested changes
One small change needed.

2023-05-10 13:48 UTC, scurker commented on docs/pages/components/Link.mdx
> +      defaultValue: 'button',
This is incorrect, there's no default value for variant.

2023-05-10 17:53 UTC, scurker approved these changes

2023-05-10 17:59 UTC, merged