Change font size of TextField to --text-size-small
dequelabs/cauldron pull request #133
Opened 2020-12-08 19:46 UTC by noahcoop

Resolve issue https://github.com/dequelabs/cauldron/issues/102

2020-12-08 21:49 UTC, schne324 requested changes
Thank you for the contribution! Unlike your [other pr](https://github.com/dequelabs/cauldron/pull/130), we actually want this change to be a part of the core library. Basically, all we need is to update [this loc](https://github.com/dequelabs/cauldron/blob/752be9519630f6174ed5652fe60862ddef92346e/packages/styles/forms.css#L151)

change it form `font-size: var(--text-size-smaller);` to `font-size: var(--text-size-small);`

2020-12-08 22:37 UTC, noahcoop commented
Sounds good, just made a new commit with the font size change in the correct file.

2020-12-09 03:41 UTC, schne324 commented
# Reviewed for security (gh action isn't working at the moment)

2020-12-09 03:41 UTC, schne324 approved these changes

2020-12-09 03:42 UTC, merged