test: convert icon tests to react testing library
dequelabs/cauldron pull request #1334
Opened 2024-02-05 02:59 UTC by anastasialanz

2024-02-26 16:47 UTC, scurker requested changes
Sorry I missed this somehow! I think we just need to add a test to run the component through jest-axe, then we should be good.

2024-02-26 16:47 UTC, scurker commented on packages/react/src/components/Icon/index.test.tsx
> +import Icon from './index';
Very very minor nit.

```suggestion
import Icon from './';
```

2024-02-27 20:49 UTC, anastasialanz commented
> Sorry I missed this somehow! I think we just need to add a test to run the component through jest-axe, then we should be good.

Updated here https://github.com/dequelabs/cauldron/pull/1334/commits/b94d0e912a01c9f47b0aa93ea88527de6eb52870

2024-02-27 22:41 UTC, scurker approved these changes

2024-02-27 22:52 UTC, merged