test: switch tooltip tabstop tests to react testing library
dequelabs/cauldron pull request #1380
Opened 2024-03-04 17:13 UTC by lsprr

Issue #1159

This PR switches the Tooltip Tabstop tests to React Testing Library.

Validation steps

- Run yarn test
- See that there are coverage percentages in the table
- Verify that the tests are converted properly

2024-03-12 22:02 UTC, scurker requested changes
Just some minor changes needed.

2024-03-12 22:02 UTC, scurker commented on packages/react/src/components/TooltipTabstop/index.test.tsx
> +  expect(screen.getByText('World')).toBeInTheDocument();
If you look at how we structure the [tooltip tests](https://github.com/dequelabs/cauldron/blob/0efb20782bc2943a438d9810d065cdf0af93efd1/packages/react/src/components/Tooltip/Tooltip.test.tsx#L67-L73) we likely want these to be very similar to that: 

```suggestion
  expect(screen.queryByRole('tooltip')).not.toBeInTheDocument();
  await fireEvent.focusIn(screen.getByRole('button'));
  expect(screen.queryByRole('tooltip')).toBeInTheDocument();
```

2024-03-12 22:02 UTC, scurker commented on packages/react/src/components/TooltipTabstop/index.test.tsx
> +  expect(screen.getByText('World')).toBeInTheDocument();
Additionally, we want to validate the accessible description as well:

```tsx
expect(
  screen.getByRole('button', { name: 'button' })
).toHaveAccessibleDescription('World');
```

2024-03-12 22:55 UTC, lsprr commented
@scruker, thank you for the feedback! I will review other pull requests to ensure everything is correct.

2024-03-13 17:16 UTC, scurker approved these changes
🚨 Reviewed for Security 🚨

2024-03-13 17:16 UTC, merged