feat(react): add prop to SearchField to render error messages
dequelabs/cauldron pull request #1400
Opened 2024-03-08 20:02 UTC by dequejosie

Follow up of https://github.com/dequelabs/cauldron/issues/1190 to render error messages as in the following case.

<img width="644" alt="Screenshot 2024-03-08 at 3 01 56 PM" src="https://github.com/dequelabs/cauldron/assets/83524297/2ceaab10-47f7-4255-8e46-76a215fede4f">

2024-03-08 21:13 UTC, scurker requested changes
@shawnsharpDQ and I discussed this, as this was a bit of a surprise to me as I'm not sure we want Search field to visually error in this way.

We discussed this on slack but we may not need any changes in Cauldron as this may be a pattern that exists per each search component.

2024-03-08 22:16 UTC, yhafez commented on docs/pages/components/SearchField.mdx
> +
I think @scurker mentioned to me in a DM that we don't need to handle error states for this component (since searches don't usually error)

2024-03-08 22:17 UTC, yhafez commented on docs/pages/components/SearchField.mdx
> +
Oh jk, looks like you already commented

2024-03-08 22:18 UTC, yhafez commented on docs/pages/components/SearchField.mdx
> +
@dequejosie is there a need for an error state in what you're implementing in the extension?

2024-03-11 15:03 UTC, closed without merging

2024-03-11 15:03 UTC, dequejosie commented
@shawnsharpDQ and I discussed about this, we will go for a different approach.