fix(styles,react): synced tag component with design
dequelabs/cauldron pull request #1602
Opened 2024-07-30 16:27 UTC by orest-s

Closes: [#1578](https://github.com/dequelabs/cauldron/issues/1578)

2024-07-31 15:17 UTC, scurker requested changes
This is missing tests for the new size (see https://github.com/dequelabs/cauldron/blob/develop/CONTRIBUTING.md#testing-strategies)

One other thing as well, can we make the existing `<Tag>` component in [documentation here](https://github.com/dequelabs/cauldron/blob/443249a184c54b728fd565654a45b31754a03e70/docs/components/ComponentProps.tsx#L55) use the small size?

2024-07-31 15:17 UTC, scurker commented on packages/react/src/components/Tag/index.tsx
> +  variant?: 'default' | 'small';
Sorry if I didn't make this clear. One of the things we want to eventually do is define our properties better (as outlined on this issue https://github.com/dequelabs/cauldron/issues/1423).

Size properties are variants, but are not an aesthetic variant. As such they should have their own property `size` to not conflict with actual variants.

2024-07-31 15:17 UTC, scurker commented on packages/styles/tag.css
> +  padding: 0px var(--space-smallest);
Nit: `0` values should be unitless in css.

```suggestion
  padding: 0 var(--space-smallest);
```

2024-07-31 15:17 UTC, scurker commented on e2e/screenshots/button-variant-tag-.png
This is slightly on me because I forgot to specify this in the requirements, but `TagButton` should have the same font requirements as the `Tag` component.

2024-07-31 19:59 UTC, scurker requested changes

2024-07-31 19:59 UTC, scurker commented on docs/pages/components/Tag.mdx
> +      name: 'variant',
Name of this should change to `size`

2024-07-31 19:59 UTC, scurker commented on e2e/screenshots/button-variant-tag-.png
You may need to update your branch, this PR was recently merged (https://github.com/dequelabs/cauldron/pull/1596) which might be part of the font size issue we're seeing here.

2024-07-31 19:59 UTC, scurker commented on packages/styles/tag.css
> -  font-size: var(--text-size-smaller);
I apologize, I messed up this requirement. The font size should be set to `--text-size-body-small` scoped to variable specific to tag.

2024-07-31 20:00 UTC, scurker commented on packages/react/src/components/Tag/index.test.tsx
> +test.only('should render small tag', () => {
No `.only`.

2024-08-01 14:44 UTC, scurker reviewed
This should be `feat` as we are adding additional features and describe the changes, e.g. _added size prop to tag and synced with designs_. Additionally, I'm double checking with @dequelabs/cauldron-design so we can get a quick design review to ensure everything is kosher.

2024-08-01 14:44 UTC, scurker commented on docs/components/ComponentProps.tsx
All of the `<Tag>` components should have the `size="small"` prop set on them here.

2024-08-01 20:32 UTC, scurker reviewed
Code Changes LGTM, just need to get a sign off from @dequelabs/cauldron-design

2024-08-02 17:50 UTC, shawnsharpDQ approved these changes

2024-08-02 18:12 UTC, scurker approved these changes

2024-08-13 14:35 UTC, merged