fix(react): remove unsupported props for alert component
dequelabs/cauldron pull request #180
Opened 2021-01-29 21:17 UTC by scurker

closes #105

2021-01-29 22:46 UTC, stephenmathieson requested changes
The demo site currently uses these props and suggests to users that they should/can:

- https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Alert/index.js#L30
- https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Alert/index.js#L44
- https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Alert/index.js#L79
- https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Alert/index.js#L93

We should either remove them from the documentation site or leave them.

Also this is a duplicate of https://github.com/dequelabs/cauldron/pull/171 (I forgot to pick this back up/finish it).

2021-02-01 14:31 UTC, scurker commented
> The demo site currently uses these props and suggests to users that they should/can:
> 
> ...
> 
> We should either remove them from the documentation site or leave them.

Ah frick, forgot to check demo. This could've been caught if the demo site was in typescript. 🤦

2021-07-28 14:58 UTC, schne324 approved these changes

2021-07-28 15:02 UTC, schne324 commented
🎉 this means we can finally tag v1 🎊

2021-07-28 15:04 UTC, merged