feat: support for dark theme buttons and links
dequelabs/cauldron pull request #321
Opened 2021-09-14 14:52 UTC by vicdq

feat: support for dark theme buttons and links

Dark theme support for buttons and links that use cauldron's ThemeProvider and '.theme-dark' in any context.

2021-09-14 14:55 UTC, vicdq commented
<img width="576" alt="Screen Shot 2021-09-14 at 8 53 35 AM" src="https://user-images.githubusercontent.com/75144504/133281366-3983e92a-80f3-4087-bd3f-9ffbfd8069bc.png"<img width="570" alt="Screen Shot 2021-09-14 at 8 54 03 AM" src="https://user-images.githubusercontent.com/75144504/133281433-d3a8acf4-0a48-4ad1-9144-57646ef3f1a6.png"><img width="573" alt="Screen Shot 2021-09-14 at 8 53 52 AM" src="https://user-images.githubusercontent.com/75144504/133281404-e030f2bf-470b-4a51-bae3-2acbb2edb674.png">

2021-09-14 14:59 UTC, vicdq commented
Please notice the following:
- single file for the dark-related CSS. If this looks good enough, we can keep adding the necessary updates for checkboxes, lists, stepper, etc in this file.
- Support for both cauldron--theme-dark (cauldron's theme-provider) and theme-dark in general (current axe-extension theme provider).

2021-09-14 16:46 UTC, scurker requested changes

2021-09-14 16:46 UTC, scurker commented on packages/styles/dark-theme.css
> +.theme-dark {
Sorry, I may not have made myself clear when we spoke in slack.

Components in cauldron should only support the `.cauldron--theme-dark` scoped class. `.theme-dark` is something local to the extension, so in the extension the theme context will need to set both classes for backwards compatibility support, but cauldron itself should be agnostic to that.

2021-09-14 16:46 UTC, scurker commented on packages/styles/dark-theme.css
> +.cauldron--theme-dark .Layout,
These styles should be co-located in their own individual css files.

For example, `button` styles should be in `button.css`, layout styles should be in `layout.css` and so on. We've been trying to move each styles to their own component CSS as it's easier to maintain individually as opposed to lumped together in a single file.

2021-09-14 16:46 UTC, scurker commented on docs/Demo/ThemeSelector.js
> +export default ThemeSelector;
We should put this in the header (see the thin/not-thin topbar toggle).

2021-09-15 15:05 UTC, scurker requested changes
Please remove the `.theme-dark` classes and put the button variables in the appropriate file

2021-09-15 15:05 UTC, scurker commented on packages/styles/button.css
> +.theme-dark .Button--primary {
No `.theme-dark`

2021-09-15 15:05 UTC, scurker commented on packages/styles/variables.css
> +.cauldron--theme-dark {
This can go in the `button.css` file

2021-09-15 16:02 UTC, vicdq commented
@scurker , should be good now. The updates for topbar and icon buttons are in this other pr: https://github.com/dequelabs/cauldron/pull/326

2021-09-15 19:01 UTC, scurker submitted a review, later dismissed
It looks like none of the hover states have been implemented correctly for the dark mode.

For example, here's how the primary button should appear when hovered:

![image](https://user-images.githubusercontent.com/1062039/133493154-2c7ac6a5-baf5-4941-805c-1a0ce9029838.png)

There should be a 1px outline of `#6CDAF2` when hovered with a 1px gap between the outline and the button border.

Also please resolve previous comments if they have been addressed, it makes it difficult to do follow up reviews.

2021-09-16 17:16 UTC, scurker requested changes
One minor request

2021-09-16 17:16 UTC, scurker commented on packages/styles/variables.css
> +  --gray: #53636e;
This isn't gray, if you look at the rgb values `83, 99, 110`, it's primarily blue with a bit of red and green. I don't think we should assign a generic variable name to something that isn't purely gray. We should name this something that will be unlikely to conflict with anything else.

Something like `--dark-accent`, we can always update it later.

2021-09-16 17:51 UTC, scurker approved these changes

2021-09-16 17:54 UTC, merged