feat: Dark theme support for checkbuttons/radios/stepper
dequelabs/cauldron pull request #328
Opened 2021-09-17 12:40 UTC by vicdq

feat: Dark theme support for checkbuttons/radios/stepper

#324

2021-09-17 12:43 UTC, vicdq commented
<img width="1091" alt="Screen Shot 2021-09-17 at 6 42 37 AM" src="https://user-images.githubusercontent.com/75144504/133784295-aa461700-5ef7-4137-ad35-5fef43256f9b.png">

<img width="581" alt="Screen Shot 2021-09-17 at 6 42 15 AM" src="https://user-images.githubusercontent.com/75144504/133784319-006ebb1b-8a30-4e37-8a9c-eb9346e3c505.png">


<img width="634" alt="Screen Shot 2021-09-17 at 6 41 41 AM" src="https://user-images.githubusercontent.com/75144504/133784336-da4d5858-16fd-4854-8356-46929f7338f4.png">

2021-09-17 14:32 UTC, scurker commented on packages/react/src/components/IconButton/index.tsx
> -  variant?: 'light' | 'dark' | 'primary' | 'secondary' | 'error';
This is a breaking change, so we need to ensure the body of the merge request includes `BREAKING CHANGE:` with a description.

2021-09-21 16:10 UTC, scurker requested changes
Radio Group dark mode does not match uxpin:

![radio group buttons not matching ux pin](https://user-images.githubusercontent.com/1062039/134205842-eb30b116-5921-4c6f-b90c-c31d106bd7a1.png)

The stepper label has a color contrast issue in dark mode:

![stepper with text description color contrast issue](https://user-images.githubusercontent.com/1062039/134205946-63bf4c22-6db6-4ee3-b4f2-e56e816f40c6.png)

2021-09-21 16:38 UTC, scurker approved these changes
Looks like I was looking at an outdated deploy preview, approved

2021-09-21 16:56 UTC, merged