feat: allow a node to be passed in as an IconButton label
dequelabs/cauldron pull request #643
Opened 2022-05-03 19:53 UTC by thuey

This allows a node to be passed in as the label for an IconButton. Allowing a node to be passed in allows consumers to include things like screen reader-only content. (see the docs example in this PR).

2022-05-03 21:28 UTC, schne324 approved these changes

2022-05-03 21:30 UTC, scurker requested changes
I don't think this will work as implemented, see how we're also setting `aria-label` below:

https://github.com/dequelabs/cauldron/blob/9d2b7bb935e642a0d20b7aca769e01185556ecdc/packages/react/src/components/IconButton/index.tsx#L78-L83

I think you're on the right track, but we also need the button to have an accessible name as well. Perhaps we should be using `<Offscreen>` there instead of just using `aria-label`.

2022-05-04 16:01 UTC, thuey commented
@scurker Good catch. I missed the "disabled" scenario.

2022-05-04 20:26 UTC, scurker approved these changes

2022-05-04 20:55 UTC, merged