Create BUG.yml
dequelabs/cauldron pull request #751
Opened 2022-09-07 18:14 UTC by abbeyperini-deque

2022-09-08 14:20 UTC, thuey requested changes

2022-09-08 14:20 UTC, thuey commented on .github/ISSUE_TEMPLATE/BUG.yml
> +labels: ["bug"]
```suggestion
labels: ["bug", "unconfirmed"]
```

2022-09-08 14:20 UTC, thuey commented on .github/ISSUE_TEMPLATE/BUG.yml
> +      description: What version of our software are you running?
```suggestion
      description: What version of cauldron did this happen with?
```

2022-09-13 14:35 UTC, stephenmathieson commented
This seems like a solution looking for a problem. Are there any examples of issues created lacking sufficient context? I do not believe this issue template will solve anything.

2022-09-13 14:48 UTC, abbeyperini-deque commented
@stephenmathieson [@scurker suggested this](https://github.com/dequelabs/cauldron/pull/743#discussion_r950400796) in the context of Hacktoberfest/the [new homepage](https://github.com/dequelabs/cauldron/blob/docs--new-homepage/docs/Home/index.js)

2022-09-13 14:58 UTC, abbeyperini-deque commented
This is less about solving a problem that doesn't exist and more about making a welcoming and easy to contribute to repo.

2022-09-13 16:43 UTC, scurker commented
> This seems like a solution looking for a problem. Are there any examples of issues created lacking sufficient context? I do not believe this issue template will solve anything.

We haven't necessarily had an issue with issue creation, but marketing is wanting to potentially promote this during hacktoberfest so there will be potentially more eyes on cauldron. This is part of the over arching theme of ensuring we have clear documentation on how to contribute.

2022-09-13 16:46 UTC, scurker submitted a review, later dismissed

2022-09-13 16:53 UTC, schne324 commented on .github/ISSUE_TEMPLATE/BUG.yml
> +      placeholder: Tell us what you expected to see!
```suggestion
      placeholder: Tell us what you expected to happen!
```

2022-09-13 16:53 UTC, schne324 commented on .github/ISSUE_TEMPLATE/BUG.yml
> +      placeholder: Tell us what you see!
```suggestion
      placeholder: Tell us what you are experiencing!
```

2022-09-13 17:24 UTC, stephenmathieson commented
> This is part of the over arching theme of ensuring we have clear documentation on how to contribute.

I don't see how adding an issue template does this, nor do the [maintainers guidelines](https://hacktoberfest.com/participation/#maintainers) from the Hacktoberfest website mention that we should add an issue template. Also, particpants don't get credit for opening issues (only PRs fixing "hacktoberfest" labelled issues).

If you all think this is worth investing the time, then go for it. I think you're wasting company time on something that will provide little/no value though.

2022-09-13 17:28 UTC, abbeyperini-deque commented
You're not wrong, but this isn't just about Hacktoberfest. This is about making the repo marketable and friendly to contribute to in general. Hacktoberfest's suggestions are bare minimum. [Ideally, we'd also have PR templates](https://virtualcoffee.io/monthlychallenges/sept-2022), but I figured that was a no go.

2022-09-13 18:05 UTC, stephenmathieson commented
> This is about making the repo marketable and friendly to contribute to in general.

I disagree that this is worth company time/will provide value 🤷

2022-09-13 18:09 UTC, scurker approved these changes

2022-09-13 18:16 UTC, scurker commented
> I don't see how adding an issue template does this

We want people outside of deque to be able to file issues, and having a descriptive issue template if they do file issues helps reduce time if the future and sets expectations if they do so.

> If you all think this is worth investing the time, then go for it. I think you're wasting company time on something that will provide little/no value though.

IMO it's a very small time investment and is worth our time. If you have further concerns about this wasting company time, this is not the appropriate venue as this is a public repository so if there's anything further to discuss, please bring it up in either via slack or email.

2022-09-13 19:44 UTC, merged